### ISSUE TITLE
Demo Plugin v0.7.0 will not start up on mysql.test

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-demo#111] opened 2020-06-11 18:20 UTC
When I upload the new release v0.7.0 of the demo plugin on my http://mysql.test.mattermost.com and try to enable it is crashes. 
Logs show info related to trying to create a channel where the name already exists (among other things)
Perhaps there is an upgrade issue with the demo plugin.
```
{"level":"error","ts":1591898526.1935163,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"fom4du8r9pft9cycarqipexuhc","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898526.3017197,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"y6bpsf5fx3f59ey6odwgbxre3c","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898528.1210191,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"cd8wkacsgp8pjd3e5sx1ryh6fc","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898528.3408728,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"4opk4n3tkpfrjbqde94cpcaq5o","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898529.451237,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"7nqki141etnqtxgqtu4rrbhopy","error":"SqlUserStore.Save: This team has reached the maximum number of allowed accounts. Contact your System Administrator to set a higher limit., "}
{"level":"error","ts":1591898530.1260083,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"qfb1qrcbejywbj7hawkzuw1btw","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898530.293569,"caller":"go-plugin@v1.2.2/stream.go:15","msg":" call to OnConfigurationChange failed, error: failed to ensure demo channels: CreateChannel: A channel with that name already exists on the same team., Channelexists id=47ioejhd67b9pnpwep1as3o4me Error 1062: Duplicate entry 'demo_plugin-z1599abuzffy8bdh4do9qzetho' for key 'Name'","plugin_id":"com.mattermost.demo-plugin","source":"plugin_stderr"}
{"level":"error","ts":1591898530.2969584,"caller":"mlog/sugar.go:23","msg":"Server configuration is not compatible","plugin_id":"com.mattermost.demo-plugin"}
{"level":"error","ts":1591898530.8210347,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"fom4du8r9pft9cycarqipexuhc","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898530.9364452,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"y6bpsf5fx3f59ey6odwgbxre3c","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898532.7847457,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"cd8wkacsgp8pjd3e5sx1ryh6fc","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898532.9855063,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"4opk4n3tkpfrjbqde94cpcaq5o","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898534.115114,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"7nqki141etnqtxgqtu4rrbhopy","error":"SqlUserStore.Save: This team has reached the maximum number of allowed accounts. Contact your System Administrator to set a higher limit., "}
{"level":"error","ts":1591898534.6991549,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"qfb1qrcbejywbj7hawkzuw1btw","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898534.862732,"caller":"mlog/log.go:175","msg":"Unable to activate plugin","plugin_id":"com.mattermost.demo-plugin","error":"failed to ensure demo channels: CreateChannel: A channel with that name already exists on the same team., Channelexists id=8g4dwmod77nkbyynaiyxjo1f1y Error 1062: Duplicate entry 'demo_plugin-z1599abuzffy8bdh4do9qzetho' for key 'Name'"}
{"level":"error","ts":1591898535.4448636,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"fom4du8r9pft9cycarqipexuhc","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898535.5482078,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"y6bpsf5fx3f59ey6odwgbxre3c","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898537.1768587,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"cd8wkacsgp8pjd3e5sx1ryh6fc","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898537.3703146,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"4opk4n3tkpfrjbqde94cpcaq5o","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898538.4109979,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"7nqki141etnqtxgqtu4rrbhopy","error":"SqlUserStore.Save: This team has reached the maximum number of allowed accounts. Contact your System Administrator to set a higher limit., "}
{"level":"error","ts":1591898538.9740536,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"qfb1qrcbejywbj7hawkzuw1btw","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898539.131942,"caller":"go-plugin@v1.2.2/stream.go:15","msg":" call to OnConfigurationChange failed, error: failed to ensure demo channels: CreateChannel: A channel with that name already exists on the same team., Channelexists id=1n46idtz47gpupjxmbrr6g8xte Error 1062: Duplicate entry 'demo_plugin-z1599abuzffy8bdh4do9qzetho' for key 'Name'","plugin_id":"com.mattermost.demo-plugin","source":"plugin_stderr"}
{"level":"error","ts":1591898539.135249,"caller":"mlog/sugar.go:23","msg":"Server configuration is not compatible","plugin_id":"com.mattermost.demo-plugin"}
{"level":"error","ts":1591898539.702591,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"fom4du8r9pft9cycarqipexuhc","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898539.8073962,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"y6bpsf5fx3f59ey6odwgbxre3c","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898541.547894,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"cd8wkacsgp8pjd3e5sx1ryh6fc","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898541.740053,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"4opk4n3tkpfrjbqde94cpcaq5o","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898542.7785597,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"7nqki141etnqtxgqtu4rrbhopy","error":"SqlUserStore.Save: This team has reached the maximum number of allowed accounts. Contact your System Administrator to set a higher limit., "}
{"level":"error","ts":1591898543.3239017,"caller":"mlog/sugar.go:23","msg":"Failed add demo user to team","plugin_id":"com.mattermost.demo-plugin","teamID":"qfb1qrcbejywbj7hawkzuw1btw","error":"JoinUserToTeam: Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}
{"level":"error","ts":1591898543.475797,"caller":"mlog/log.go:175","msg":"Unable to activate plugin","plugin_id":"com.mattermost.demo-plugin","error":"failed to ensure demo channels: CreateChannel: A channel with that name already exists on the same team., Channelexists id=nbg69tj3gfy6icpyoswosou5pa Error 1062: Duplicate entry 'demo_plugin-z1599abuzffy8bdh4do9qzetho' for key 'Name'"}
```
I think error where the user cannot join certain team due to email validation would be expected but the channel creation issue is preventing the demo plugin from starting up.

Steps: 
- Navigate to https://mysql.test.mattermost.com
- Remove older version of the demo plugin
- Download new release of the demo plugin
- Upload to https://mysql.test.mattermost.com
- Attempt to enable the plugin

**Comment by DHaussermann** [comment] 2020-06-11 18:20
@hanzei is it possible that this error occurred before but with PR https://github.com/mattermost/mattermost-plugin-demo/pull/109 we now prevent start-up when channel creation fails?

**Comment by hanzei** [comment] 2020-06-12 12:23
> @hanzei is it possible that this error occurred before but with PR #109 we now prevent start-up when channel creation fails?

Indeed, that is the case.

It seams like there a two issues:
1. `This team has reached the maximum number of allowed accounts. Contact your System Administrator to set a higher limit.` Given that the limit is reached, the demo plugin can't add it's demo user.
2 `Email must be from a specific domain (e.g. @example.com). Please ask your team or system administrator for details., "}` Could you check if any team as a email restriction?

**Comment by DHaussermann** [comment] 2020-06-12 13:19
@hanzei yes some teams have the email restriction and since the demo-plugin user is not a bot, they are not exempt from needing a matching email.

I wounder what you think the best solution to this is. 0/5 it seems the last PR was a bit too aggressive in making sure the user can be added to all teams. It seems not too uncommon that some teams will not be joinable. Should we start the plugin even if that isn't the case?

**Comment by hanzei** [comment] 2020-06-15 10:30
From looking a the code it seams like the plugin already start successfully if the demo user can't join a team. Could the plugin not starting be caused by 1. from https://github.com/mattermost/mattermost-plugin-demo/issues/111#issuecomment-643242485?

**Comment by hanzei** [comment] 2020-06-28 14:48
@DHaussermann Assigning this back to you

**Comment by DHaussermann** [comment] 2020-07-29 19:05
After further investigation - I see no further bug to fix here. 
When the demo plugin user is unable to join a team (for various reasons), this is logged but does not cause a crash. The plugin **can** be enabled even if the user cannot join each team. 

Closing this task.

**Closed** 2020-07-29 19:05 UTC
Labels: Type/Bug
